//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int UserID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Sex { get; set; }
        public string RealName { get; set; }
        public string AliasName { get; set; }
        public string Position { get; set; }
        public Nullable<bool> IsLocked { get; set; }
        public int LoginCount { get; set; }
        public string IDCardNo { get; set; }
        public Nullable<int> UserGroupID { get; set; }
        public string Remark { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public string QQ { get; set; }
        public string PersonalRemark { get; set; }
        public Nullable<int> OnlineStatus { get; set; }
        public string OnlineStatusDesc { get; set; }
        public Nullable<System.DateTime> LastLoginTime { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
    }
}
